name: taming
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.12
  - pip=23.3.1
  - cudatoolkit=11.7
  - pytorch=2.0.1
  - torchvision=0.15.2
  - numpy=1.24.4
  - pip:
    - albumentations==1.3.1
    - opencv-python==4.8.1
    - pudb==2023.1
    - imageio==2.31.6
    - imageio-ffmpeg==0.4.9
    - pytorch-lightning==1.0.8
    - omegaconf==2.3.0
    - test-tube>=0.7.5
    - streamlit==1.28.1
    - einops==0.6.1
    - more-itertools>=8.0.0
    - transformers==4.33.0
    - -e .
